# Generated by Django 5.1.4 on 2024-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('userid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
