# Generated by Django 5.1.4 on 2024-12-21 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsAndResources',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.project')),
                ('required_materials', models.TextField(blank=True, null=True)),
                ('labour', models.TextField(blank=True, null=True)),
                ('machinery', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('tools', models.TextField(blank=True, null=True)),
                ('consumables', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
