# Generated by Django 5.1.4 on 2024-12-22 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_projectcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExecution',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.project')),
                ('client_type', models.TextField(blank=True, null=True)),
                ('time_of_visit', models.TextField(blank=True, null=True)),
                ('record', models.TextField(blank=True, null=True)),
                ('site_visit_remarks', models.TextField(blank=True, null=True)),
                ('identification_of_problems', models.TextField(blank=True, null=True)),
                ('solutions', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('site_visit_documentation', models.FileField(blank=True, null=True, upload_to='site_visit_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('quotation_submission', models.FileField(blank=True, null=True, upload_to='quotation_submission/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('quotation_approval', models.FileField(blank=True, null=True, upload_to='quotation_approval/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
