# Generated by Django 5.1.4 on 2024-12-23 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_workexecution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.project')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_left', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('next_expected_date', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEntry',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client_detail', models.TextField()),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'png', 'jpg', 'jpeg'])])),
                ('payment_date', models.DateField()),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='login.billing')),
            ],
        ),
    ]
