# Generated by Django 5.1.4 on 2024-12-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_billing_paymententry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='amount_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='next_expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='next_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='client_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='mode_of_payment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='paymententry',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
