# Generated by Django 4.2.17 on 2025-01-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_billing_amount_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexecution',
            name='client_type',
        ),
        migrations.AddField(
            model_name='workexecution',
            name='client',
            field=models.CharField(blank=True, choices=[('Company', 'Company'), ('Institutions', 'Institutions'), ('Consultants', 'Consultants'), ('Engineers', 'Engineers'), ('Architects', 'Architects'), ('Individuals', 'Individuals')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workexecution',
            name='through',
            field=models.CharField(blank=True, choices=[('Phone call', 'Phone call'), ('Whatsapp', 'Whatsapp'), ('Email', 'Email')], max_length=20, null=True),
        ),
    ]
