# Generated by Django 4.2.17 on 2025-01-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_workexecution_client_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexecution',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
