# Generated by Django 4.2.17 on 2025-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_workexecution_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
