# Generated by Django 4.2.17 on 2025-02-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_usergroup_preregistereduser_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexecution',
            name='client',
            field=models.CharField(choices=[('Company', 'Company'), ('Institutions', 'Institutions'), ('Consultants', 'Consultants'), ('Engineers', 'Engineers'), ('Architects', 'Architects'), ('Individuals', 'Individuals')], default='Individuals', max_length=20),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='client_name',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='identification_of_problems',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='recommendations',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='record',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='site_visit_remarks',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='solutions',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='through',
            field=models.CharField(choices=[('Phone call', 'Phone call'), ('Whatsapp', 'Whatsapp'), ('Email', 'Email')], default='Phone call', max_length=20),
        ),
        migrations.AlterField(
            model_name='workexecution',
            name='time_of_visit',
            field=models.TextField(default='Not Specified'),
        ),
    ]
