# Generated by Django 4.2.17 on 2025-02-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_workexecution_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialsandresources',
            name='consumables',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='materialsandresources',
            name='equipment',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='materialsandresources',
            name='labour',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='materialsandresources',
            name='machinery',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='materialsandresources',
            name='required_materials',
            field=models.TextField(default='Not Specified'),
        ),
        migrations.AlterField(
            model_name='materialsandresources',
            name='tools',
            field=models.TextField(default='Not Specified'),
        ),
    ]
