# Generated by Django 4.2.17 on 2025-02-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_materialsandresources_consumables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcompletion',
            name='client_feedback',
            field=models.TextField(default='No feedback provided'),
        ),
        migrations.AlterField(
            model_name='projectcompletion',
            name='client_rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
